### ISSUE TITLE
ARM64 support in VS2022

### ISSUE THREAD

**Issue by MagicAndre1981** [tmyt/vstoastnotifier#10]
Microsoft now provides [ARM64 version since VS2022 17.4](https://learn.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022), so having this [extension on ARM64](https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/) would be nice for users of the ARM64 dev kit:

```xml
<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.4,18.0)">
   <ProductArchitecture>arm64</ProductArchitecture>
</InstallationTarget>
```

**Comment by tmyt** [comment]
I'll support it later

**Comment by tmyt** [comment]
ARM64 environment just supported!
