### ISSUE TITLE
incompatible with VS2019 Update 1 (16.1)

### ISSUE THREAD

**Issue by MagicAndre1981** [tmyt/vstoastnotifier#7]
The addin can't be used since VS2019 Update 1 (16.1).

> 18 months ago, we sent an email to extension partners announcing the _deprecation of synchronous auto-loading of extension packages. A year ago, we followed up with a blog post with more details that outlined that synchronously auto-loaded package would be unsupported in a future version of Visual Studio._ **That version is 16.1.**

![image](https://user-images.githubusercontent.com/8274816/56041360-d2efe680-5d38-11e9-9208-8971273dba97.png)

So convert it to Asyncpackage to fix it before 16.1 gets released as stable.

**Comment by tmyt** [comment]
Uh,,, yes,, yes, I working to support Asyncpackage.
Conversion is bit difficult to support all VS2012 to VS2019. I working hardly to release update before 16.1 release.

**Comment by MagicAndre1981** [comment]
ok, so the best would be an old sync version for 2012-2013 and an async for VS2015 - 2019

**Comment by tmyt** [comment]
I just supported AsyncPackage in version 1.8. You can take newer version from VS market place now.

**Comment by MagicAndre1981** [comment]
perfect, it works fine in 16.1.0 Preview 1.0
