### ISSUE TITLE
doesn't work on some projects

### ISSUE THREAD

**Issue by yasartaymaz** [tmyt/vstoastnotifier#8]
hi there, i use it on multiple projects and multiple computers. for example on my home pc, i use win 10 and vs 19 latest. a netcore3.1 project is ok but other netcore3.1 project is NOT ok.
not: 2 of the solutions have multiple projects in it.

**Comment by tmyt** [comment]
Hello,

Hmm.... It is strange behavior.
Would you provide the reproducing project file to me?

**Comment by yasartaymaz** [comment]
thank you, here it is:
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <AssemblyVersion>2021.3.4.1808</AssemblyVersion>
    <UserSecretsId>50714991-c95e-44d8-b36f-5bc7a673c0aa</UserSecretsId>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Definitions\Controllers\MachineTypeDefinitionsController.cs" />
  </ItemGroup>
 <ItemGroup>
    <ProjectReference Include="..\Business\Business.csproj" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptJSXEmit>React</TypeScriptJSXEmit>
    <TypeScriptModuleKind />
    <TypeScriptCompileOnSaveEnabled>False</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptOutFile />
    <TypeScriptOutDir />
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptMapRoot />
    <TypeScriptSourceRoot />
  </PropertyGroup>

</Project>

**Comment by yasartaymaz** [comment]
thank you, here it is:
[https://gist.github.com/yasartaymaz/f0f5389e546510db1539bfa61a1d3acf](url)

**Comment by yasartaymaz** [comment]
any update sir?

**Comment by tmyt** [comment]
Sorry toooooo late to respond to you.
It is historical bug. Fixed in release 1.9.1, you can download from VS Market place now.
If you use VS2019 or earlier, please replace to "ToastNotifier (Legacy)".
