### ISSUE TITLE
Visual studio 2022 support

### ISSUE THREAD

**Issue by Dyxos** [tmyt/vstoastnotifier#9]
Hello dear sir,

I was wondering if you are planning to support visual studio 2022 in the near future.

**Comment by tmyt** [comment]
Hi!
I planned to support VS2022. but 2022 has little changes from older VSs, requires some changes to sources.
I targeted to release in this month.

**Comment by tmyt** [comment]
I just released for VS2022.

**Comment by Dyxos** [comment]
Thank you very much for your time!
